In [1]:
import pyvista as pv
import numpy as np
from pathlib import Path

In [2]:
DIR_BASE = Path('/home/daniel/sphinxsys-build/cases_jan/heart/bin/output/0')
files = sorted(DIR_BASE.rglob('*.npz'))

In [4]:
data = np.load(files[130])
data['XYZ']
data['Voltage']

array([[1.0787993e-04],
       [1.0764931e-04],
       [9.8077478e-05],
       ...,
       [9.8613518e-01],
       [9.8875868e-01],
       [9.8919356e-01]], dtype=float32)

In [4]:
xx, yy, zz = np.arange(2), np.arange(2), np.arange(2)
xx, yy, zz = np.meshgrid(xx, yy, zz)
print(xx.ravel())
print(yy.ravel())
print(zz.ravel())

print(np.add(xx, 1).ravel())
# grid = np.array([np.array([x, y, z]) for x in np.arange(-55, 35)
#                      for y in np.arange(-75, 5) for z in np.arange(-35, 35)])

[0 0 1 1 0 0 1 1]
[0 0 0 0 1 1 1 1]
[0 1 0 1 0 1 0 1]
[1 1 2 2 1 1 2 2]


In [5]:
a = 1
b = 1
c = 1
d = a, b, c
print(d)


(1, 1, 1)


In [34]:
mat = np.empty((1,1,1), dtype=int)
mat[0,(0,0)]=1
print(mat)

[[[1]]]
